name: CD

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  cd:
    if: github.event.pull_request.merged == true
    name: CD
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1

      - name: Bump version
        run: |
          flutter pub get
          flutter pub run version
          git add pubspec.yaml
          git commit -m "bumped version to $(flutter pub run cider version)"
      
      - name: Push updated app version
        run: git push

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --release

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: tester_1
          file: build/app/outputs/apk/release/app-release.apk
