name: CD

on:
  pull_request:
    # types:
    #   - closed
    branches:
      - main

jobs:
  cd:
    # if: github.event.pull_request.merged == true
    name: CD
    runs-on: ubuntu-22.04
    environment: ${{ github.ref_name }}
    steps:
      - run: echo ${{ vars.MY_NAME }}
      - name: Config git user
        run: |
          git config --global user.email "kittipong.t@bafs-id.co.th"
          git config --global user.name "GitHub Actions"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1

      - name: Run Test
        run: |
          flutter pub get
          flutter analyze
          flutter test

      - name: Bump version
        run: |
          flutter pub get
          flutter pub run cider bump build
          git add pubspec.yaml
          git commit -m "bumped version to $(flutter pub run cider version)"

      - name: Generate release notes
        run: |
          git log --pretty="format:%b" --merges latest-build...HEAD > ./release_notes.txt
          cat ./release_notes.txt

      - name: Build APK
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release --flavor ${{ vars.FLAVOR }} -t lib/main_${{ vars.FLAVOR }}.dart

      - name: Upload to Firebase app distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ vars.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT_DEV }}
          groups: tester_1
          file: build/app/outputs/apk/${{ vars.FLAVOR }}/release/app-${{ vars.FLAVOR }}-release.apk
          releaseNotesFile: release_notes.txt

      - name: Update app version
        run: git push

      - name: Update latest build tag
        run: |
          git tag -f latest-build
          git push -f origin latest-build
