name: CD

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  cd:
    if: github.event.pull_request.merged == true
    name: CD
    runs-on: ubuntu-22.04
    steps:
      - name: Set up env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "FLAVOR=dev" >> $GITHUB_ENV
            echo "FILE_NAME=main.dart" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/uat" ]; then
            echo "FLAVOR=uat" >> $GITHUB_ENV
            echo "FILE_NAME=main.dart" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "FLAVOR=dev" >> $GITHUB_ENV
            echo "FILE_NAME=main.dart" >> $GITHUB_ENV
            echo "FIREBASE_APP_ID=${{ vars.FIREBASE_APP_ID_DEV }}" >> $GITHUB_ENV
            echo "CREDENTIAL_TARGET=CREDENTIAL_FILE_CONTENT_DEV" >> $GITHUB_ENV
          fi

      - name: Config git user
        run: |
          git config --global user.email "kittipong.t@bafs-id.co.th"
          git config --global user.name "GitHub Actions"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1

      - name: Log info
        run: |
          echo "FLAVOR: ${{ env.FLAVOR }}"
          echo "FILE_NAME: ${{ env.FILE_NAME }}"
          echo "FIREBASE_APP_ID: ${{ env.FIREBASE_APP_ID }}"
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
          echo $(java --version)
          flutter --version

      - name: Run Test
        run: |
          flutter pub get
          flutter analyze
          flutter test

      - name: Bump version
        run: |
          flutter pub get
          flutter pub run cider bump build
          git add pubspec.yaml
          git commit -m "bumped version to $(flutter pub run cider version)"

      - name: Generate release notes
        run: |
          git log --pretty="format:%s" --merges latest-build...HEAD > ./release_notes.txt
          cat ./release_notes.txt

      - name: Build APK
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release --flavor ${{ env.FLAVOR }}

      - name: Upload to Firebase app distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ env.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets[env.CREDENTIAL_TARGET] }}
          groups: tester_1
          file: build/app/outputs/apk/release/app-release.apk
          releaseNotesFile: release_notes.txt

      - name: Update app version
        run: git push

      - name: Update latest build tag
        run: |
          git tag -f latest-build
          git push -f origin latest-build
