name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Get branch name
        run: git rev-parse --abbrev-ref HEAD

      - name: Log changes
        run: |
          git fetch -f origin --tags
          git log --pretty="format:%s" latest-build...${{ github.event.pull_request.head.sha }} > ./release_notes.txt

      - run: cat -n ./release_notes.txt
      - run: cat ./tags.txt
      - run: git rev-list -n 1 latest-build

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
