name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.22.1"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
