name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: "11"
  FLUTTER_VERSION: "3.22.1"

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: composite
        uses: ./.github/actions/target
        with:
          who-to-greet: "Alice"
          java-version: ${{ env.JAVA_VERSION }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

      - run: exist 1
  call-reusable-1:
    needs: [test]
    uses: ./.github/workflows/reusable.yml
    with:
      your-name: "Alice"
