name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: git rev-parse --abbrev-ref HEAD

      - name: Github ref
        run: echo ${{ github.ref }}

      - run: exist 1
  call-reusable-1:
    uses: ./.github/workflows/reusable.yml
    with:
      your-name: "Alice"
