name: Test

on:
  pull_request:
    branches:
      - main

  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: git rev-parse --abbrev-ref HEAD

      - name: Github ref
        run: echo ${{ github.ref }}

      - name: Dump context
        run: ${{ toJSON(github) }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
