name: Test

on:
  pull_request:
    types:
      - closed
    branches:
      - main

  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: git rev-parse --abbrev-ref HEAD

      - name: Github ref
        run: echo ${{ github.ref }}

      - name: Dump context
        run: ${{ toJSON(github) }}
